/**
 * Core type definitions for Recursion Cinema
 * These interfaces define the data structures used throughout the visualization system.
 */

/**
 * Frame representing a single execution step in the recursion.
 * Generated by StepGenerator for each line of code execution.
 */
export interface FrameObject {
  /** Unique identifier for this frame */
  id: string;
  /** Line number in the source code (1-indexed, positive integer) */
  lineNo: number;
  /** Current depth in the call stack (0-indexed, non-negative integer) */
  stackDepth: number;
  /** Local variables and their values at this execution point */
  variables: Record<string, number | string>;
  /** Type of action: CALL (new invocation), RETURN (unwinding), CALC (computation) */
  action: 'CALL' | 'RETURN' | 'CALC';
  /** Name of the function being executed */
  functionName: string;
  /** Return value when action is 'RETURN' */
  returnValue?: number | string;
  /** ID of the parent frame that called this function */
  parentFrameId?: string;
  /** Function parameters for display (separate from local variables) */
  parameters?: Record<string, number | string>;
}

/**
 * Visual state of a Stack Card in the Stack Tower.
 * Controls animations and appearance of each card.
 */
export interface StackCardState {
  /** Reference to the corresponding FrameObject */
  frameId: string;
  /** 3D position for the card (x offset creates tower effect) */
  position: { x: number; y: number; z: number };
  /** Whether this card is the currently executing frame */
  isActive: boolean;
  /** Whether this card is paused waiting for child to return */
  isFrozen: boolean;
  /** Whether this card is in the process of returning */
  isReturning: boolean;
  /** Glow effect color: green for base case, blue for active, none otherwise */
  glowColor?: 'green' | 'blue' | 'none';
}

/**
 * Tree node for React Flow visualization.
 * Represents a function call in the recursion tree.
 */
export interface RecursionTreeNode {
  /** Unique identifier matching the frame ID */
  id: string;
  /** Node data for rendering */
  data: {
    /** Display label (function name with args) */
    label: string;
    /** Variables at this call */
    variables: Record<string, number | string>;
    /** Whether this node is currently active */
    isActive: boolean;
    /** Return value if this call has completed */
    returnValue?: number | string;
  };
  /** Position in the tree layout */
  position: { x: number; y: number };
  /** Parent node ID for tree structure */
  parentId?: string;
}

/**
 * Animation event in the timeline.
 * Used by AnimationController to sequence visual effects.
 */
export interface AnimationEvent {
  /** Type of animation to perform */
  type: 'CARD_ENTER' | 'CARD_FREEZE' | 'CARD_GLOW' | 'CARD_EXIT' | 'ORB_TRAVEL';
  /** ID of the element to animate */
  targetId: string;
  /** Duration of the animation in milliseconds */
  duration: number;
  /** Delay before starting in milliseconds */
  delay: number;
  /** Additional data for the animation */
  payload?: Record<string, unknown>;
}

/**
 * Current state of playback controls.
 */
export interface PlaybackState {
  /** Whether animation is currently playing */
  isPlaying: boolean;
  /** Index of the current frame being displayed */
  currentFrameIndex: number;
  /** Total number of frames in the sequence */
  totalFrames: number;
  /** Playback speed multiplier (0.5x to 2x) */
  speed: number;
}

/**
 * Result of code validation by StepGenerator.
 */
export interface ValidationResult {
  /** Whether the code is valid for visualization */
  isValid: boolean;
  /** List of validation errors if any */
  errors: string[];
  /** Detected recursion pattern if recognized */
  detectedPattern?: 'factorial' | 'fibonacci' | 'tree_traversal' | 'custom';
}

/**
 * Structured error from StepGenerator
 */
export interface StepGeneratorError {
  /** Error code for programmatic handling */
  code: string;
  /** Human-readable error message */
  message: string;
  /** Severity level: error (blocking), warning (non-blocking), info (informational) */
  severity: 'error' | 'warning' | 'info';
  /** Suggestion for how to fix the issue */
  suggestion?: string;
}

/**
 * Complete result from frame generation including errors and warnings
 */
export interface GenerationResult {
  /** Generated frames (may be empty if errors occurred) */
  frames: FrameObject[];
  /** Structured errors from generation */
  errors: StepGeneratorError[];
  /** Warning messages */
  warnings: string[];
  /** Whether generation was successful (frames generated or only non-blocking errors) */
  isSuccess: boolean;
  /** Whether the output was truncated due to frame/depth limits */
  wasTruncated: boolean;
}

/**
 * Action types for highlighting in the code editor.
 */
export type ActionHighlightColor = {
  CALL: string;
  RETURN: string;
  CALC: string;
};

/**
 * Default highlight colors for different action types.
 */
export const ACTION_COLORS: ActionHighlightColor = {
  CALL: '#2196F3',    // Blue for function calls
  RETURN: '#4CAF50',  // Green for returns
  CALC: '#FFC107',    // Yellow for calculations
};
